# 网址：http://wiki.ros.org/costmap_2d/hydro/staticmap
obstacle_range: 5.0
raytrace_range: 5.0
# robot_radius: 0.45
inflation_radius: 0.55
cost_scaling_factor: 1.0
max_obstacle_height: 3
min_obstacle_height: 0.1
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true, expected_update_rate: 0}

trinary_costmap: true
lethal_cost_threshold: 51

# unknown_cost_value: -1
# map_topic: "map"
# first_map_only: false
# subscribe_to_updates: false
# track_unknown_space: true
# use_maximum: false
# trinary_costmap: true