# 网址：http://wiki.ros.org/costmap_2d
local_costmap:
   global_frame: odom
   robot_base_frame: nav_link
   update_frequency: 10.0
   publish_frequency: 5.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.05
   transform_tolerance: 0.5
   map_type: costmap

#    plugins:
#      - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
# #     - {name: social_layer,        type: "social_navigation_layers::ProxemicLayer"}   
# #     - {name: social_pass_layer,        type: "social_navigation_layers::PassingLayer"}  
# #     - {name: static_layer, type: "costmap_2d::StaticLayer"} 
#      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
 
#   #Configuration for the sensors that the costmap will use to update a map   
#    obstacle_layer:
#      observation_sources: scan  
#      scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0} 
#    inflation_layer: 
#       inflation_radius: 0.1
