# 网址：http://wiki.ros.org/dwa_local_planner
DWAPlannerROS:
    acc_lim_x: 1.5
    acc_lim_y: 1.5
    acc_lim_theta: 2.5
    max_vel_trans: 0.3 # absolute value
    min_vel_trans: 0 # absolute value
    max_vel_x: 0.3
    min_vel_x: -0.3
    max_vel_y: 0.3
    min_vel_y: -0.3
    max_vel_theta: 0
    min_vel_theta: 0
    max_rot_vel: 0.25 # absolute value
    min_rot_vel: 0.0 # absolute value 

    yaw_goal_tolerance: 0.2
    xy_goal_tolerance: 0.1
    latch_xy_goal_tolerance: false

    sim_time: 2.0
    sim_granularity: 0.025
    vx_samples: 20
    vy_samples: 20
    vth_samples: 40
    controller_frequency: 5.0

    path_distance_bias: 48.0 # default 32.0
    goal_distance_bias: 24.0 # default 24.0
    occdist_scale: 0.1 # default 0.01
    forward_point_distance: 0.325
    stop_time_buffer: 0.2
    scaling_speed: 0.25 # absolute value
    max_scaling_factor: 0.2
    publish_cost_grid: false

    oscillation_reset_dist: 0.05

    prune_plan: true
