# 网址：http://wiki.ros.org/dwa_local_planner
DWAPlannerROS:
    acc_lim_x: 1.2
    acc_lim_y: 1.2
    acc_lim_theta: 1.2
    max_vel_trans: 0.3 # absolute value
    min_vel_trans: 0 # absolute value
    max_vel_x: 0.3
    min_vel_x: -0.3
    max_vel_y: 0.3
    min_vel_y: -0.3
    max_vel_theta: 0.3
    min_vel_theta: -0.3
    max_rot_vel: 0.5 # absolute value
    min_rot_vel: 0.0 # absolute value

    yaw_goal_tolerance: 0.1
    xy_goal_tolerance: 0.1
    latch_xy_goal_tolerance: false

    sim_time: 1.0
    sim_granularity: 0.025
    vx_samples: 3
    vy_samples: 3
    vth_samples: 3
    controller_frequency: 5.0

    path_distance_bias: 32.0
    goal_distance_bias: 24.0
    occdist_scale: 0.01
    forward_point_distance: 0.325
    stop_time_buffer: 0.2
    scaling_speed: 0.25 # absolute value
    max_scaling_factor: 0.2
    publish_cost_grid: false

    oscillation_reset_dist: 0.05

    prune_plan: true