# 网址：http://wiki.ros.org/costmap_2d
global_costmap:
   global_frame: map
   robot_base_frame: nav_link
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 0.5
   default_tolerance: 1
   map_type: costmap

#    plugins:
# #     - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
#      - {name: static_layer, type: "costmap_2d::StaticLayer"} 
   
#      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
#    inflation_layer: 
#       inflation_radius: 0.1
      