obstacle_range: 100.0
raytrace_range: 100.0
robot_radius: 0.165
inflation_radius: 0.1
max_obstacle_height: 0.6
min_obstacle_height: 0.2
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 6}

trinary_costmap: true
lethal_cost_threshold: 51

# 默认参数，具体见 staticmap 介绍 http://wiki.ros.org/costmap_2d/hydro/staticmap
# unknown_cost_value: -1
# map_topic: "map"
# first_map_only: false
# subscribe_to_updates: false
# track_unknown_space: true
# use_maximum: false
# trinary_costmap: true